### ISSUE TITLE
dont work on FS25

### ISSUE THREAD

**Issue by Kahhb** [Timmeey86/FS25_ForestryHelper#29]

**Comment by Timmeey86** [comment]
Of course the Zip File for FS22 does not work for FS25.

The FS25 version is queued for review on mod hub.

**Comment by Kahhb** [comment]
ok ok , tyvm for yor work! keep going sir!

**Comment by DuffCal** [comment]
> Of course the Zip File for FS22 does not work for FS25.
> 
> The FS25 version is queued for review on mod hub.

Is there a way to download the FS25 version from your github page?  I see the link for it but when I download it the FS22 file downloads.  Thanks for all your hard work!

**Comment by DuffCal** [comment]
> > Of course the Zip File for FS22 does not work for FS25.
> > The FS25 version is queued for review on mod hub.
> 
> Is there a way to download the FS25 version from your github page? I see the link for it but when I download it the FS22 file downloads. Thanks for all your hard work!
> 
> ![image](https://private-user-images.githubusercontent.com/190960734/393558782-8dba3b97-eb20-49c7-ba3d-65f70d184aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDQ4MDEsIm5iZiI6MTczMzcwNDUwMSwicGF0aCI6Ii8xOTA5NjA3MzQvMzkzNTU4NzgyLThkYmEzYjk3LWViMjAtNDljNy1iYTNkLTY1ZjcwZDE4NGFlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQwMDM1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDM1OTA0M2U5Yjg0MGJmOWJiYzRiMjZiNTJiZDk5MmY2ZWI2NmIzNGM1Y2VjOTE1ZmIzNTc1NTc4MWVlMWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f_9yxhEobVeZzhCttkMsPKuD3PWVdPg5QaXreuYLcqQ)

Also do you have a page where I can donate to you for your modding time?

**Comment by Timmeey86** [comment]
[FS25_ForestryHelper.zip](https://github.com/user-attachments/files/18068524/FS25_ForestryHelper.zip)

This is the version which is queued for modhub.
There's no donation link, I'm not doing this for the money ;-)

**Comment by DuffCal** [comment]
> [FS25_ForestryHelper.zip](https://github.com/user-attachments/files/18068524/FS25_ForestryHelper.zip)
> 
> 
> 
> This is the version which is queued for modhub.
> 
> There's no donation link, I'm not doing this for the money ;-)

Thanks very much!

But if someone wanted to tank you for your hard work what would be the best way to buy you lunch?  Thanks very much for your hard work!
