### ISSUE TITLE
Deadwood mission error

### ISSUE THREAD

**Issue by jufcar** [Timmeey86/FS25_ForestryHelper#31]
When i do a deadwood mission all is fine until i try to cut a felled tree into smaller pieces with the komatsu harvester while your mod is active. If i try to do that i get a lot of Error: Running LUA method 'draw'. in the log.
[log.txt](https://github.com/user-attachments/files/18163962/log.txt)

(there are only 3 entries in my log as i deleted the rest of it for a smaller file size)

**Comment by Timmeey86** [comment]
Hi, it appears you are using an older state of my mod (unfortunately all of them have version 1.0.0.0 since they were queued for mod hub. 

Do you know how to create your own zip from the newest commit on this repository? If not, I can create one for you, but only in around 6-8 hours from now

**Comment by jufcar** [comment]
Thanks for the replay, yes i can do it myself and will try again.
